### ISSUE TITLE
Turn off logging at Error level?

### ISSUE THREAD

**Issue by yonathansebhastian** [fcopardo/EasyRest#24]
Hi Fransisco, Thanks for this easyrest library. I was using it on a test project and found that the entire rest call is logged in the logcat. Is there anyway to turn off the log? Thanks!

UPDATE: after looking at the code, it seems I need to turn off debug mode. Is this possible?

 ` E/EasyRest: Call type:GET
    Starting time:Mon May 14 20:57:20 GMT+07:00 2018
    Request Headers`

**Comment by fcopardo** [comment]
Hi Yonathan! thanks for your interest. There's a method for that, EasyRest.setDebugMode(boolean debugMode). Set it to false and the logs will go away.

Happy coding!

**Comment by yonathansebhastian** [comment]
Thank you! It seems to work fine now. I put the method in the Application class
